// Requires a running local server with real data. Set PLAYWRIGHT_MODULE to an installed Playwright module.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');const fs=require('fs');
fs.mkdirSync('.tmp/niche',{recursive:true});
(async()=>{
const browser=await chromium.launch({headless:true}); const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
const page=await context.newPage();let aiCalls=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/niche-angles'))aiCalls++});
await page.goto('http://localhost:3000/niche?group=FIN%20COMP');const desk=page.locator('#opportunity-workbench');await desk.waitFor({timeout:60000}); await page.getByRole('button',{name:'Inspect channel similarities'}).waitFor();
await page.waitForFunction(()=>document.querySelectorAll('#opportunity-workbench aside button[aria-pressed]').length>0);console.log('PASS live FIN COMP loaded');
assert.equal(await desk.locator('article').count(),12);await page.getByRole('button',{name:/Show more ·/}).click();assert.equal(await desk.locator('article').count(),24);
await page.getByRole('textbox',{name:'Search video titles or channels'}).fill('zzzz-no-result');await page.getByText('No videos match this view').waitFor();await page.getByRole('button',{name:'Show all tracked videos',exact:true}).click();
await page.getByLabel('Filter channel',{exact:true}).selectOption('@explains101');assert.ok((await desk.locator('article').allTextContents()).every(s=>s.includes('@explains101')));assert.equal(await desk.getByText('What these videos have in common',{exact:true}).count(),0);await page.getByLabel('Filter channel',{exact:true}).selectOption('');
await page.getByLabel('Minimum source outlier score',{exact:true}).selectOption('10');assert.ok((await desk.locator('article').allTextContents()).every(s=>s.includes('10.0 source score')));
await page.getByLabel('Sort videos',{exact:true}).selectOption('pace');await page.getByLabel('Sort videos',{exact:true}).selectOption('recent');console.log('PASS search / channel / source score / sort / pagination');
await desk.getByRole('button',{name:/Add to shortlist:/}).first().click();await desk.getByRole('button',{name:/Shortlist ·/}).click();assert.equal(await desk.locator('article').count(),1);await desk.getByRole('button',{name:/Copy brief/}).click();await page.getByText('Brief copied',{exact:true}).waitFor();const brief=await page.evaluate(()=>navigator.clipboard.readText());assert.ok(brief.includes('total views')&&brief.includes('https://www.youtube.com/watch?v='));
await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(new Error('denied'))}}));await desk.getByRole('button',{name:/Copy brief/}).click();await page.getByRole('textbox',{name:'Research brief',exact:true}).waitFor();assert.ok((await page.getByRole('textbox',{name:'Research brief',exact:true}).inputValue()).includes('total views'));await desk.getByRole('button',{name:/Remove from shortlist:/}).click();assert.equal(await desk.locator('article').count(),0);console.log('PASS shortlist / copy success / clipboard failure fallback / remove');
await desk.locator('aside button[aria-pressed]').first().click();assert.ok(await desk.locator('article').count()>0);assert.equal(await page.getByLabel('Minimum source outlier score',{exact:true}).inputValue(),'0');assert.equal(await desk.getByRole('button',{name:/Shortlist ·/}).getAttribute('aria-pressed'),'false');console.log('PASS topic selection clears conflicting filters');
await page.getByRole('button',{name:'Inspect channel similarities'}).click();await page.locator('#channel-similarity').waitFor();await page.getByRole('button',{name:/vocabulary overlap. Inspect shared words/}).nth(1).click();assert.ok((await page.locator('#channel-similarity').innerText()).includes('Shared words:'));console.log('PASS matrix reveal / shared vocabulary');
const evidence=page.getByRole('button',{name:'Show the evidence',exact:true});for(let i=0;i<await evidence.count();i++){await evidence.nth(i).click();assert.ok(['channels','outliers','trend','peers'].includes(await page.evaluate(()=>document.activeElement.id)));}console.log('PASS recommendation evidence reveals and focuses target');
await page.setViewportSize({width:390,height:844});await page.locator('main').evaluate(e=>e.scrollTop=0);await page.screenshot({path:'.tmp/niche/mobile-top.png'});await desk.scrollIntoViewIfNeeded();await page.screenshot({path:'.tmp/niche/mobile-desk.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByLabel('Explore a topic',{exact:true}).selectOption({index:1});assert.ok(await page.locator('main').evaluate(e=>e.scrollWidth<=e.clientWidth));console.log('PASS mobile 390px / topic control / no horizontal overflow');
await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Shorts',exact:true}).click();await desk.waitFor();assert.equal(await desk.getByRole('button',{name:/Shortlist ·/}).innerText(),'Shortlist · 0');await page.getByRole('button',{name:/GTA Gaming/}).click();await page.getByRole('heading',{name:'GTA Gaming',exact:true}).waitFor();await page.getByRole('button',{name:'Long-form',exact:true}).click();await page.getByRole('button',{name:'Inspect channel similarities'}).click();await page.waitForTimeout(2500);await page.screenshot({path:'.tmp/niche/thin.png'});console.log('PASS format / niche switching and shortlist reset');
await page.goto('http://localhost:3000/niche?group=does-not-exist');await desk.waitFor({timeout:60000});assert.ok(!(await page.getByRole('heading',{level:1}).innerText()).includes('does-not-exist'));console.log('PASS invalid niche URL fallback');
assert.equal(aiCalls,0);assert.deepEqual(errors,[]);console.log('PASS no automatic AI calls / no page errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
